# GATILHOS POSGRE SQL

 * UM GATILHO É UMA FUNÇÃO CHAMADA AUTOMATICAMENTE SEMPRE QUE OCORRE
 UM EVENTO COMO INSERÇÃO, ATUALIZAÇÃO OU EXCLUSÃO. NESTA SEÇÃO,
 VOCÊ APRENDERA SOBRE GATILHOS E COMO GERENCIALOS COM EFICÁCIA;
 
  - INTRODUÇÃO AO GATILHO POSTGRESQL: OFERECE UMA BREVE VISÃO GERAL DOS GATILHOS POSTGRESQL, POR QUE VOCÊ DEVE USAR
  GATILHOS E QUANDO USÁ-LOS;
  
  - CRIAR GATILHO: MOSTRA PASSO A PASSO COMO CRIAR MEU PRIMEIRO GATILHO NO POSTGRE SQL;
  
  - ELIMINR GATILHO: DECREVE AS ETAPAS DE COMO USAR A DROP TRIGGER ISTRUÇÃO PARA EXCLUIR UMA GATILHO DE UMA TABELA;
  
  - ALTERAR GATILHO: ORIENTA VOCÊ SOBRE COMO USAR A ALTER TRIGGER ISTRUÇÃO PARA RENOMEAR UMA GATILHO;
  
  - DESATIVAR GATILHO: MOSTRA COMO DESATIVAR UM GATILHO OU TODOS OS GATILHOS QUE PERTECEM A UMA TABELA;
  
  - HABILITAR GATILHOS: APRENDA COMO HABILITAR UM GATILHO OU TODOS OS GATILHOS ASSOCIADOS A UMA TABELA;
  