-- ALTERAR TABELAS COM (ALTER TABLE) E VISUALIZAR RELACIONAMENTOS ENTRE TABELAS

-- ALTERAR ESTRUTURA DE UMA TABELA APOS CRIALAS, ACRECENTANDO OU EXCLUINDO ATRIBUTOS(CAMPOS)
-- USAMOS PARA ISSO O COMANDO ALTER TABLE

-- COMO EXCLUIR UMA COLUNA DE UMA TABELA EXISTENTE
-- SINTAXE: ALTER TABLE nome_tabela DROP COLUMN nome_coluna_que_quero_excluir;

-- EXEMPLO:
ALTER TABLE livro DROP COLUMN id_autor;

-- PODE-SE ADICIONAR COLUNAS:
-- SINTAXE:
-- ALTER TABLE nome_tabela ADD nome_nova_coluna tipo_de_dado_coluna constraints_se_tiver;
-- EXEMPLO: ADICIONANDO A COLUNA ID_AUTOR FAZENDO ELA SER UMA CHAVE ESTRANGEIRA, RECEBENDO UMA CHAVE PRIMARIA DA TABELA AUTORES
ALTER TABLE livro ADD CONSTRAINT fk_id_autor FOREIGN KEY(id_autor) REFERENCES autores(id_autor);
-- EXEMPLO: ADD A TABELA LIVRO UMA NOVA COLUNA QUE VAI SER UMA CHAVE ESTRNGEIRA REFERENCIANDO A COLUNA DA TABELA EDITORA AS 2 TABELAS VÃO ESTAR RELACIONADAS
ALTER TABLE livro ADD COLUMN id_editora smallint not null;
ALTER TABLE livro ADD CONSTRAINT fk_id_editora FOREIGN KEY(id_editora) REFERENCES editoras(id_editora);

-- ALTERAR COLUNAS MUDANDO O TIPO DE DADOS:
ALTER TABLE livro ALTER COLUMN id_autor SMALLINT;

-- ADD UMA CHAVE PRIMARIA A UMA TABELA QUE AINDA NÃO TEM UMA DEFINIDA MAS DEVE EXISTIR UMA COLUNA QUE VAI RECEBER A CHAVE PRIMARIA:
-- obs: a coluna id_cliente tem que existir
ALTER TABLE clientes ADD PRIMARY KEY(id_cliente)
