-- criação de um banco de dados, comandos para poder criar um banco de dados AULA 1
-- PARA CRIAR UM BANCO DE DADOS:
                  (opcional)
CREATE DATABASE [IF NOT EXISTS] nome_BD;
-- IF NOT EXISTS: PREVINE DE CRIAR UM BANCO DE DADOS EXISTENTES NO SERVIDOR;

-- EX:
CREATE DATABASE biblioteca;

-- VER OS BANCOS DE DADOS QUE JA EXISTE:
SHOW DATABASES;

-- NO MYSQL TODA VEZ QUE VOU UDAR UM BANCO DE DADOS TENHO QUE DIZER E ESPECIFICAR QUEM E O BANCO:
-- PARA ISSO USO O COMANDO USE:
USE nome_banco_dados;

-- VIZUALIZAR BANCO DE DADOS QUE ESTA SENDO USADO:
SELECT DATABASE();

-- PARA EXCLUIR UM BANCO DE DADOS EXISTENTES:
DROP DATABASE nome_BD;

-- MOSTRAR TABELAS EXISTENTES NO BANCO DE DADOS:
SHOW TABLES;