-- CONSTRAINTS(RESTRIÇÕES APLICAVEIS EM TABELAS DE BANCO DE DADOS)
-- REGRAS QUE APLICAM EM COLUNAS DE UMA TABELA, LIMITAR OS DADOS QUE VOU INSERIR
-- PODE APLICAR QUANDO ESTA CRIANDO AS TABELAS E COLUNAS OU APLICAR DEPOIS DE CRIADAS

-- PRINCIPAIS RESTRIÇÕES,EXITEM MAIS:
-- *NOT NULL
-- *UNIQUE
-- *PRIMARY KEY
-- *FOREIGN KEY
-- *DEFAULT

-- NOT NULL(NÃO NULO):
-- IMPOE A COLUNA A NÃO ACEITAR VALORES NULOS
-- OBRIGA A COLUNA A SEMPRE TER UM VALOR

-- UNIQUE(UNICO):
-- IDENTIFICA DE FORMA UNICA CADA REGISTRO DA TABELA
-- IMPEDINDO A DUPLICAÇÃO DE DADOS

-- PRIMARY KEY(CHAVE PRIMARIA):
-- IDENTIFICA DE FORMA UNICA CADA REGISTRO DO BANCO DE DADOS
-- NÃO ACEITA VALORES NULOS
-- CADA TABELA TEM QUE TER UMA CHAVE PRIMARIA E APENAS SO UMA CHAVE PRIMARIA

-- FOREIGN KEY(CHAVE ESTRANGEIRA):
-- EM UMA TABELA ELA E UMA CHAVE QUE VAI APONTAR PARA OUTRA CHAVE DE OUTRA TABELA

-- DEFAULT(VALOR PADRÃO):
-- E USADA PARA INSERIR UM VALOR PADRÃO EM UMA COLUNA
-- O VALOR PADRÃO SERA ADICIONADO A CADA NOVO REGISTRO INSERIDO
-- CASO NENHUM OUTRO VALOR NA INSERÇÃO FOR ADICIONADO
