-- DEFININDO PREVILEGIOS DE ACESSO AO BANCO DE DADOS COM GRANK E REVOKE
-- GRANT ATRIBUI UM PRIVILEGIO / REVOKE PARA RETIRAR UM PREVILEGIO

-- VERIFICANDO QUAIS SÃO OS USUARIOS EXISTENTES NO MYSQL:
SELECT user,host FROM mysql.user;

-- VENDO PERMISSÕES DE ACESSO QUE UM USUARIO PODE TER:
SHOW GRANTS FOR Samuel@localhost;

-- EXPLICANDO SOBRE PREVILEGIOS:

-- PREVILEGIOS QUE TRABALHAM COM DADOS:
SELECT,INSERT,UPDATE,EXECUTE,DELETE;

-- PREVILEGIOS PARA MODIFICAR ESTRUTURA DE UM BANCO DE DADOS:
CREATE,ALTER,DROP,CREATE VIEWS,TRIGGER,INDEX,CREATE ROUTINE,ALTER ROUTINE;

-- PRIVILEGIOS ADMINISTRATIVOS:
CREATE USER,SHOW DATABASES,SHUTDOWN,RELOAD;

-- OUTROS PRIVILEGIOS
ALL,GRANT OPTION,USAGE;

-- NIVEIS DE PREVILEGIO:
  -- GLOBAL: O USARIO TEM ACESSO A TABELAS DE TODOS OS BANCOS DE DADOS.
  -- DATABASE: DA AO USUARIO ACESSO A TODAS AS TABELAS DE UM BANCO DE DADOS ESPECIFICO.
  -- TABLE: O USUARIO TEM ACESSO A TODAS AS COLUNAS ESPECIFICAS DE UM BANCO DE DADOS
  -- COLUMN: O USUARIO POSSUI ACESSO APENAS A COLUNAS ESPECIFICAS EM UMA DETERMINADA TABELA.
  
-- TABELA GRANTTABLES ARMAZENA INFORMAÇÕES DE PREVILEGIOS SOBRE OS USUARIOS

-- TRABALHANDO COM ATRIBUIÇÃO DE PREVILEGIOS:

-- CRIAR UM USUARIO SEM PREVILEGIO NENHUM:
-- GRANT - COMANDO /USAGE - PREVILEGIO QUE VOU ATRIBUIR /ON - ESCOPO DO PREVILEGIO / *.* - (*)TODOS BANCOS DE DADOS . (*)TODAS AS TABELAS /
-- julia@localhost - usuario que não existe e vai ser criado pelo comando GRANT(localhost - a partir da maquina que esta que se pode fazer login) /
-- IDENTIFIED BY - dando uma senha para o usuario
GRANT USAGE -> ON *.* -> TO julia@localhost IDENTIFIED BY '1234'; 

-- CRIANDO USUARIO COM PREVILEGIOS GLOBAIS
GRANT ALL -> ON *.* -> TO alexandre IDENTIFIED BY '1234' -> WITH GRANT OPTION; 

-- VERIFICAR SE DE CERTO
SHOW GRANTS FOR nome_usuario@local_login;

-- DANDO PREVILEGIOS DE MANIPULAÇÃO DE DADOS PARA UM USUARIO:
GRANT SELECT, UPDATE,INSERT,DELETE,EXECUTE -> ON biblioteca.* -> TO Samuel@localhost;

