-- GERENCIAMENTO DE USUARIOS DO SISTEMA - CRIAR,CONSULTAR,RENOMEAR E EXCLUIR.

-- CONSULTANDO USUARIOS EXISTENTES(EM UM TABELA INTERNA CHAMADA USER) TABELA DO SISTEMA DO SERVIDOR MYSQL;
SELECT user FROM mysql.user;

-- PARA SABER EM QUAIS HOSTS PODEM SE CONECTAR ESSES USUARIOS
SELECT user,host FROM mysql.user;

-- CRIANDO UMA NOVO USUARIO SINTAXE:
CREATE USER nome_usuario@a_partir_de_onde_vai_se_logar IDENTIFIED BY 'senha';

-- CRIANDO UM NOVO USUARIO PESSOAL:   -- localhost(significa: pode se logar a partir dessa maquina mesmo).
CREATE USER Samuel@localhost IDENTIFIED BY '1234456';

-- VENDO SE DEU CERTO, LISTANDO OS USUARIO EXISTENTES NO BANCO:
SELECT user,host FROM mysql.user;

-- CRIANDO UM NOVO USUARIO QUE POSSA SE LOGAR A PARTIR DE QUALQUER LUGAR, INCLUSIVE REMOTAMENTE BASTA NÃO INFORMAR nenhum host de login:
CREATE USER ana  IDENTIFIED BY '00012';

-- VENDO SE DEU CERTO, LISTANDO OS USUARIO EXISTENTES NO BANCO:
SELECT user,host FROM mysql.user;
-- se no host estiver o simbolo % e porque pode se logar de qualquer lugar

-- CRIANDO UM USUARIO SEM SENHA
CREATE USER marcos@localhost;

-- CONFIGURANDO UMA SENHA PARA ESSE USUARIO RECEM CRIADO SEM SENHA:
-- SINTAXE:
SET PASSWORD FOR 'nome_usuario@mpartir_local_login' = PASSWORD('senha');
-- USANDO:
SET PASSWORD FOR 'marcos'@'localhost' = PASSWORD('1234');

-- EXCLUINDO UM USUARIO:
DROP USER nome_usuario;

