-- INDEXAÇÃO DE TABELAS EM MYSQL
-- INDICES:
-- INDICES SÃO EMPREGADOS EM CONSULTAS PARA AJUDAR A ENCONTRAR REGISTROS COM UM VALOR ESPECIFICO EM UMA COLUNA DE FORMA RAPIDA
-- OU SEJA, AUMENTAR O DESEMPENHO NA EXECUÇÃO DE CONSULTAS;
-- COM INDICES O MYSQL VAI DIRETO A UMA LINHA EM VEZ DE BUSCAR TODA A TABELA ATE ENCONTRAR OS REGISTROS QUE IMPORTAM
-- O MY SQL CRIA INDICES AUTOMATICAMENTE PARA RESTRIÇÕES COMO: PRIMARY KEY,FOREING KEY,UNIQUE

-- ALEM DISSO PODEMOS CRIAR INDICES PARA OUTRAS COLUNAS
-- INDICES CLUSTERIZADOS:
-- ALTERAM A FORMA FISICAMENTE DE COMO OS DADOS SÃO ARMAZENADOS, ELE ORDENA OS DADOS NO BANCO DE DADOS DE ACORDO COM OS INDICES
-- A TABELA SO PODE TER UM INDICE CLUSTERIZADO, ELE FICA ONDE ESTA A CHAVE PRIMARIA, EM SUA AUSENCIA FICA ONDE TEM UMA RESTRIÇÃO UNIQUE

-- INDICE NÃO CLUSTERIZADO: A FORMA COM OS DADOS SÃO ARMAZENADOS NÃO E ALTERADA, UM OBJETO SEPARADO E CRIADO NA TABELA
-- APONTAANDO PARA OS VALORES ORIGINAIS DA TABELA, UMA TABELA PODE TER VARIOS INDICES DESSE TIPO

-- COMO CRIAR OS INDICES NO MYSQL EM UMA TABELA EXISTENTE:
-- SINTAXE: CREATE INDEX nome_indice ON nome_tabela(coluna1_que_Sera_indexada[ASC | DESC],coluna2); 

-- COM ALTER TABLE: ALTER TABLE nome_tabela ADD INDEX nome_indice(COLUNAS);

SHOW INDEX nome_tabela; -- mostrar indices em uma tabela

-- CONTEUDO IMCOMPLETO DESANIMEI DA AULA