-- TIPOS DE DADOS COMUNS EM MY SQL
-- DADOS QUE COSTITUEM AS COLUNAS DAS TABELAS
-- OS MAIS COMUNS
-- explicação

-- TIPOS NUMERICOS(INTEIROS):
-- (INT, TINYINT,SMALLINT,BIGINT) : A DIFERENÇA ENTRE ELES E O ESCOPO QUE CADA UM ALCANÇA

-- COM CASAS DECIMAIS(COM VIRGULAS):
-- DECIMAL(M,D) = M : numero total de digitos do numero D : qtd de numeros apos a virgula
-- o padrão e ex: 10.0
-- FLOAT(M,D);

-- TIPOS DE DADOS STRINGS:
-- CHAR(M) : M = QTD DE CARACTERES QUE A STRING VAI TER
-- VARCHAR(M)  : STRING DE TAMANHO VARIAVEL(TIPO VETOR)

-- TIPOS DE DADOS QUE ARMAZENA BINARIOS(DE IMAGENS,MUSICAS, ETC..):
-- BLOB,MEDIUMBLOB,TINYBLOB

-- GUARDAR VALORES TEXTUAIS MUITOS GRANDES:
-- MEDIUMTEXT
-- LONGTEXT

-- TIPOS DATA E HORA:
-- DATA = DATE 01/01/1000 ATE 31/12/9999, NO FORMATO YYYY-MM-DD
-- DATA E HORA: DATETIME : FORMATO YYYY/MM/DD - HH:MM:SS
-- HORA: HH-MM-SS
 

